version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/hydra-core/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/hydra-sample-implementation/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/sample-a/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/sample-b/" # Location of package manifests
    schedule:
      interval: "daily"
