version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/hydra/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/hydra-showcase/" # Location of package manifests
    schedule:
      interval: "daily"
