version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/hydra/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.springframework.boot:*"
        update-types: ["version-update:semver-major"]  
  - package-ecosystem: "maven"
    directory: "/hydra-showcase/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.springframework.boot:*"
        update-types: ["version-update:semver-major"]  
