hydra:
  enable-security: true
  high-availability: false
  web:
    protocol: http
server:
  error:
    whitelabel:
      enabled: false
  port: 8761
spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/local_example"
    username: postgres
    password: pass123
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 10m
      validation-query: SELECT 1