hydra:
  enable-security: true
  high-availability: false
  web:
    protocol: http
server:
  error:
    whitelabel:
      enabled: false
  port: 8761
spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true