hydra:
  secret: "7788348a-43b5-403df9dd823-2504-4abd-8633-27025dacfc014b7-b3430a4d6129"
  enable-security: true
  high-availability: false
  web:
    protocol: http
server:
  error:
    whitelabel:
      enabled: false
  port: 8761
spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/local_example"
    username: postgres
    password: pass123
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 10m
      validation-query: SELECT 1