name: Run build with tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: 19
          cache: maven
      - name: Build medusa-ui with tests
        working-directory: ./hydra
        run: mvn clean install --no-transfer-progress -D"spring.profiles.active"=dev
      - name: Build hydra-showcase with tests
        working-directory: ./hydra-showcase
        run: mvn -U clean install --no-transfer-progress -D"spring.profiles.active"=dev
